### ISSUE TITLE
Support jooq 3.19.*

### ISSUE THREAD

**Issue by yueliangwen** [zero88/jooqx#174] opened 2024-02-24 05:42 UTC
**Is your feature request related to a problem? Please describe.**
Do you have any plan to support jooq 3.19.*? I have a try, but Caused by: java.lang.NoSuchMethodError: 'org.jooq.Converter org.jooq.Field.getConverter()'.

**Comment by zero88** [comment] 2024-02-26 06:43
Thank you for your report. Let me try my best to get back to you as soon as possible.
I assumed you're using v2.0.0-rc1

**Comment by zero88** [comment] 2024-03-02 04:48
Hi @yueliangwen 
I cannot reproduce your error. 
I thought there were some dependency conflicts, please make sure you override Vert.x and jOOQ version in your build descriptor (pom.xml or gradle.build)

I closed this ticket, however, if anything is unclear, please leave a message.
Thanks

**Comment by yueliangwen** [comment] 2024-03-02 08:57
[jooqx.tar.gz](https://github.com/zero88/jooqx/files/14468635/jooqx.tar.gz)

Steps to Reproduce：

1、Download the jooqx.tar.gz
2、Read the README.adoc, ./gradlew clean run
3、Configure the PostgreSQL instance
<img width="859" alt="image" src="https://github.com/zero88/jooqx/assets/1107708/2bd293a4-758f-496b-b42c-76c4df37e32d">
4、curl http://localhost:8888/dump, you will see the problem.

Change the jooq version to 3.17.21, there's no problem.

**Comment by zero88** [comment] 2024-03-04 06:15
thank you for the reproduction. That helps me a lot to detect a reason: 
since `jooq` >= `3.17` uses java 17 as the default. Not pretty sure why jooq@3.17.x is still fine, but jooq >= 3.18.x raises an error. Somehow, `jooqx` is not compatible anymore with `jooq` when running java 17, which leads to `NoSuchMethodError` at runtime.

I reproduced it by unit-test that already re-compiled jooqx on java17, then the error didn't happen

I will find a time this week to make a release to make jooqx lib compatible in java17+

**Comment by zero88** [comment] 2024-03-16 11:39
Hi @yueliangwen 
Could you pls try jooqx version `2.0.0-rc.1:jdk17`? 
Unfortunately, something's weird in gradle build, then I cannot keep the previous rc version.

```gradle
  implementation("io.github.zero88:jooqx:2.0.0-rc.1:jdk17")
  implementation("io.github.zero88:jooqx-spi:2.0.0-rc.1:jdk17")
```

That is a matrix version
| jooqx            | jooq    | jdk    |
|------------------|---------|--------|
| 2.0.0-rc1       | < 3.18  | any    |
| 2.0.0-rc.1:jdk17 | >= 3.18 | jdk17+ |

I will upgrade to jdk17 as default in the next release.

Thank you for your patience!!!

**Comment by yueliangwen** [comment] 2024-03-16 14:31
Hi @zero88 
I rerun some simple examples, it works well. Thanks for your great job.

**Closed** 2024-05-13 06:42 UTC
Labels: T: Feature
